### ISSUE TITLE
Missing pieces before NLog 5.0 release candidate

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog#4274]
Have now made a draft document of the upcoming release:

https://github.com/NLog/NLog.github.io/pull/158

Have the following tasks remaining:

- [x] Extract Msmq-Target into NLog.Msmq-package (and drop NLog.Extended-package)
- [x] Extract Wcf-Target into NLog.Wcf-package
- [x]  ~~Extract Mail-Target into NLog.SmtpClient-package~~
- [x] Extract Database-Target into NLog.Database-package #4351
- [x]  ~~Extract Network-Target (Along with NLogViewerTarget + ChainsawTarget) into NLog.NetworkSocket-package~~
- [x]  ~~Extract HostNameLayoutRenderer into NLog.NetworkSocket-package~~
- [x]  ~~Extract LocalIpAddressLayoutRenderer into NLog.NetworkSocket-package~~
- [x]  ~~Extract WebService-Target into NLog.WebRequest-package~~
- [x] Extract PerformanceCounter-Target into NLog.PerformanceCounter-package
- [x] Extract PerformanceCounterLayoutRenderer into NLog.PerformanceCounter-package
- [x] Extract ImpersonatingTargetWrapper into NLog.WindowsIdentity-package (if possible)
- [x] Extract WindowsIdentityLayoutRenderer into NLog.WindowsIdentity-package
- [x] Extract OutputDebugStringTarget into NLog.OutputDebugStringTarget
       - Leave behind DebugSystemTarget that can call System.Diagnostics.Debug.WriteLine
- [x] Extract RegistryLayoutRenderer into NLog.WindowsRegistry-package
- [x] Remove QueryPerformanceCounterLayoutRenderer
       - The layout is called `${qpc}` which also doesn't give much meaning.
       - Maybe call it NLog.HighPrecisionTiming since nothing to do with Windows PerformanceCounters.
       - But that name is also misleading since there is no high precision because the layoutrender infers a huge overhead.
       - Think it should be removed and one should instead use `${scopetiming}` or `${processtime}`
- [x] `Layout<T>` should be merged with ~~#3656~~ #4306
- [x] Add support for better type-name loading to resolve #2944
- [x] Add support for dependency injection of singleton services through `LogFactory.Setup().SetupExtensions()`
- [x] Add support for fluent setup of NLog-configuration - #4323 
- [x] Obsolete NLog.Fluent and introduce optimized LogEventBuilder - #4325 
- [x] Remove build and publish of `NLog.config`-nuget-package
- [x] Major version bump to 5.0-preview1 and publish nuget-package - #4468
- [x] [Issues that need attention after releasing NLog 5.0 Preview 1](https://github.com/NLog/NLog/pulls?page=1&q=is%3Apr+label%3A%22needs+documentation+on+wiki%22+is%3Aclosed+-label%3A%22documentation+done%22+is%3Amerged&utf8=%E2%9C%93) (needs documentation on wiki)

**Comment by snakefoot** [comment]
Because of Travis-build-pipeline issues, then waiting for #4271 to be approved and Travis being disabled for this project.

**Comment by snakefoot** [comment]
@304NotModified Since we are working on extracting exotic stuff from the NLog-package. Would it be a big issue if the QueryPerformanceCounterLayoutRenderer `${qpc}` was just dropped into the sea of the forgotten? (Without being extracted into its own nuget-package).

**Comment by snakefoot** [comment]
@304NotModified Thinking that it might be an idea to create a meta-package for the NLog-project, that includes the following nuget-packages:
- NLog
- NLog.Database
- NLog.NetworkSocket
- NLog.WebRequest
- NLog.SmtpClient
- NLog.HttpClient (one day)

The meta-package should automatically bump its version, whenever updating one of its dependencies.

**Comment by snakefoot** [comment]
Starting to convince myself that a lot of the convience with NLog is lost when extracting these into seperate packages:
- NetworkTarget.cs
- MailTarget.cs
- WebServiceTarget

Did a comparison of adding NLog to a simple ConsoleApp with AppTriming. It grew from 11 MByte to 21 MByte. When using NLog without the above packages then it became 19 MByte. 

Maybe it should just be an exercise in removing Windows-specific stuff from the respository so people on other platforms can approach the Nlog-project. Along with removing DatabaseTarget to fix the code-analysis warnings because it can execute SQL.

**Comment by 304NotModified** [comment]
> Thinking that it might be an idea to create a meta-package

I like meta packages. Best if both worlds. I think the metal package should be called NLog and the "core" NLog.Core

**Comment by 304NotModified** [comment]
> Starting to convince myself that a lot of the convenience with NLog is lost when extracting these into seperate package

What's lost if we've a meta package?

**Comment by snakefoot** [comment]
I have decided to bravely revert the changes of extracting MailTarget + NetworkTarget + WebServiceTarget, so they become part of the default NLog-project.

Will instead just focus on extracting the database-target and the other exotic targets that are very Windows specific.

Made some stabs on stripping all targets and all layoutrenderers from the NLog-project, and still the AppTriming could not reduce below 19 MByte. Think somebody has to take a microscope and check parts of the NLog-infrastructure that prevents triming.

**Comment by snakefoot** [comment]
> What's lost if we've a meta package?

That it just generates a lot of inconvience without providing any real benefit. All loosers and no winners.

**Comment by 304NotModified** [comment]
The real benefit is that an user could choose to include less targets. That is also nice for security reasons. 

Also I think in the future those should be separate repositores and builds, so the build don't take ages.

**Comment by snakefoot** [comment]
>  That is also nice for security reasons.

Since NLog doesn't start doing random things on its own, but only perform logging to the targets that has been configured. Then I don't see this an issue. The only security issue that I see is the automatic assembly loading, and that will be now disabled in NLog 5.

I'm no going to revert everything, but I will just let WebServiceTarget and MailTarget glide back into the NLog-project. Neither of them gives any overhead in the build-process.

**Comment by snakefoot** [comment]
Believe the remaining pieces for completing NLog 5.0 are now ready as pull-requests.

**Comment by snakefoot** [comment]
Now just need #4351 for extracting DatabaseTarget into its own nuget-package.

**Comment by snakefoot** [comment]
> @304NotModified So that's what I mean before, maybe trim the [milestone](https://github.com/NLog/NLog/milestone/61)

Have now removed all my own issues where no pull-request is ready. Maybe you could do the same?

**Comment by 304NotModified** [comment]
Yes, will do that

**Comment by snakefoot** [comment]
> Yes, will do that

You want me to move the outstanding issues to NLog 6.0 ?

**Comment by snakefoot** [comment]
All checkboxes has been ticked. Created #4468 with major-version bump.

**Comment by snakefoot** [comment]
[Issues that need attention after releasing NLog 5.0 Preview 1](https://github.com/NLog/NLog/pulls?page=3&q=is%3Apr+label%3A%22needs+documentation+on+wiki%22+is%3Aclosed+-label%3A%22documentation+done%22+is%3Amerged&utf8=%E2%9C%93)

**Comment by snakefoot** [comment]
Completed updating the necessary wiki-pages, but one that I leave for @304NotModified to complete.

**Comment by snakefoot** [comment]
Closing since NLog 5.0-rc1 is now out. Still waiting for pending wiki-update: #4716
